### ISSUE TITLE
How to add more function in class

### ISSUE THREAD

**Issue by KevinJue** [gowithfloat/FLWebView-Swift#1]
Hello,
I'm trying to add a function in classes (uiWebview + WKwebview) to override url of webview and reload it but unfortunately it's a fail.

Could you help me, i've doing this in iOS but I can't translate it in swift with your configuration.

```
    [self.webView loadRequest:[NSURLRequest requestWithURL:[NSURL URLWithString:self.webappURL]]];
    [[NSURLCache sharedURLCache] removeAllCachedResponses];
    [self.webView reload];
```

**Comment by EBusch** [comment]
@KevinJue are you trying to do it within the loadRequestFromString method of FLWKWebView?

The Swift equivalent of what you are trying to accomplish here would be the following

```
func loadRequestFromString(urlNameAsString: String!) {
        self.loadRequest(NSURLRequest(URL: NSURL(string: urlNameAsString)!))
        NSURLCache.sharedURLCache().removeAllCachedResponses()
        self.reload()
    }
```

**Comment by KevinJue** [comment]
@EBusch  i choose this option currently but i would like remove cache and reload url in specific case that why i would like create an other function.

i could add parameters in function but i think, for futur request it's will be appreciated to know what i have to do for implement a new function

**Comment by EBusch** [comment]
@KevinJue 

Certainly, the first step would be to add it to the provider. For example, you would expand to something more like...

FLWebViewProvider.swift

```
func loadRequestFromString(urlNameAsString: String!)    
func loadRequestFromString(urlNameAsString: String!, whileRemovingCaches: Bool!)
```

And then inside FLWKWebView.swift we could use the previous method but also remove the caches first

```
func loadRequestFromString(urlNameAsString: String!, whileRemovingCaches: Bool!) {
        NSURLCache.sharedURLCache().removeAllCachedResponses()
        loadRequestFromString(urlNameAsString)
}
```

And you could do the asme for the UIWebView portion as well!

**Comment by KevinJue** [comment]
@EBusch  thanks i think i was doing something wrong in FLWKWebView.swift when i tried.

i will try soon in my project.

You can close i think.
Cheers
